package com.darya.jobassistant.applicationmaterials.preparation;

/**
 * Sprint 10 Step 5: one provider-neutral, ready-to-deliver document - the user-visible file name
 * persisted/generated by {@code RenderApplicationMaterialsUseCase} (Step 4), its MIME type, and its
 * already-loaded bytes (via {@code FileStoragePort#load}). Deliberately carries no {@code Path},
 * Spring {@code Resource}, Telegram {@code InputFile}, or storage key - a delivery channel (e.g.
 * Telegram) converts this into whatever upload shape it needs, but never reaches past it into
 * {@code FileStoragePort} or a storage adapter itself.
 */
public record PreparedDocument(String fileName, String contentType, byte[] content) {

    public PreparedDocument {
        if (fileName == null || fileName.isBlank()) {
            throw new IllegalArgumentException("Prepared document fileName must not be blank");
        }
        if (contentType == null || contentType.isBlank()) {
            throw new IllegalArgumentException("Prepared document contentType must not be blank");
        }
        if (content == null || content.length == 0) {
            throw new IllegalArgumentException("Prepared document content must not be empty");
        }
    }
}
