package com.darya.jobassistant.personalprojects.aggregate;

import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

/**
 * Sprint 11 Step 5: framework-free domain aggregate for one Personal Project (V29's {@code
 * personal_project} plus its highlight/technology children) - {@link PersonalProjectRepositoryPort}
 * loads and saves this as one unit.
 *
 * <h2>Why an independent aggregate root per project, not one wrapper collection</h2>
 *
 * Unlike Career History (one {@code career_history} row wrapping the candidate's whole company
 * graph), each {@link PersonalProject} is saved and versioned <b>independently</b> - there is no
 * {@code personal_projects} wrapper row. Mirroring Career History's whole-graph-replace pattern at
 * the collection level would recreate the exact identity-instability problem this design exists
 * to solve, just one level down: replacing the *entire* project graph on every save would
 * regenerate every sibling project's (and its children's) ids on any single project edit, not only
 * on an unrelated Candidate Profile edit. Giving each project its own row, its own {@link
 * #version}, and its own {@link PersonalProjectRepositoryPort#save} call means:
 *
 * <ul>
 *   <li>a Candidate Profile save never touches this table at all;
 *   <li>saving project A never rewrites project B's id, {@link #highlights}, or {@link
 *       #technologies};
 *   <li>{@link #id} is therefore a stable reference a future AI tailoring step can select/order
 *       against without the underlying fact ever being silently regenerated by unrelated writes.
 * </ul>
 *
 * <p>{@link #highlights}/{@link #technologies} <em>are</em> still replaced as a whole every time
 * <em>this specific project</em> is saved (see {@code PersonalProjectRepositoryAdapter}) - the
 * same Tier-1 convention already accepted for Candidate Profile's skills/languages/preferences,
 * just scoped to one project instead of the whole candidate. Their ids are stable against
 * everything except a re-save of this exact project.
 *
 * <p>{@link #id} is {@code null} for a project not yet persisted; {@link #version} is the
 * optimistic-locking token a caller must supply unchanged from a prior load - see {@link
 * PersonalProjectRepositoryPort#save}.
 */
public record PersonalProject(
        UUID id,
        UUID candidateProfileId,
        String name,
        String description,
        String url,
        LocalDate startDate,
        LocalDate endDate,
        int displayOrder,
        List<PersonalProjectHighlight> highlights,
        List<PersonalProjectTechnology> technologies,
        long version
) {

    public PersonalProject {
        if (candidateProfileId == null) {
            throw new IllegalArgumentException("Personal project candidate profile id must not be null");
        }
        name = PersonalProjectValidation.requireNonBlank(name, "Personal project name must not be blank");
        description = PersonalProjectValidation.blankToNull(description);
        url = PersonalProjectValidation.blankToNull(url);
        PersonalProjectValidation.requireNonNegative(displayOrder, "Personal project display order must not be negative");
        if (startDate != null && endDate != null && endDate.isBefore(startDate)) {
            throw new IllegalArgumentException("Personal project end date must not precede start date");
        }
        if (version < 0) {
            throw new IllegalArgumentException("Personal project version must not be negative");
        }

        highlights = PersonalProjectValidation.copySortedByDisplayOrder(highlights, PersonalProjectHighlight::displayOrder);
        technologies = PersonalProjectValidation.copySortedByDisplayOrder(technologies, PersonalProjectTechnology::displayOrder);

        PersonalProjectValidation.requireUniqueDisplayOrders(
                highlights, PersonalProjectHighlight::displayOrder, "Duplicate personal project highlight display order");
        PersonalProjectValidation.requireUniqueDisplayOrders(
                technologies, PersonalProjectTechnology::displayOrder, "Duplicate personal project technology display order");
        // Case-insensitive, trimmed: "Kafka"/"kafka"/" Kafka " are the same factual technology -
        // see PersonalProjectTechnology's javadoc. Deliberately not applied to project names
        // across a candidate's projects - a human-readable name is presentation content, not
        // identity, and is never database- or domain-level-unique here.
        PersonalProjectValidation.requireUniqueNormalized(
                technologies, PersonalProjectTechnology::name, "Duplicate personal project technology name (case-insensitive)");
    }

    /** Convenience constructor for a not-yet-persisted project (no id, version 0). */
    public PersonalProject(
            UUID candidateProfileId, String name, String description, String url, LocalDate startDate, LocalDate endDate,
            int displayOrder, List<PersonalProjectHighlight> highlights, List<PersonalProjectTechnology> technologies) {
        this(null, candidateProfileId, name, description, url, startDate, endDate, displayOrder, highlights, technologies, 0L);
    }
}
