package com.darya.jobassistant.applicationmaterials.generation.model;

import java.util.List;

/**
 * Sprint 10 Step 3: the tailored CV half of a {@link GeneratedApplicationMaterials} result -
 * semantic document content only, never presentation/layout concerns (fonts, page size, margins,
 * colors - those belong to a future document-rendering step). {@link #languages} is populated
 * directly from {@code CandidateProfile.languages()} by the caller, never generated by the AI -
 * there is nothing to tailor about a fixed list of known languages, so asking the AI to reproduce
 * it would only add hallucination surface for zero benefit.
 */
public record GeneratedCv(
        String headline,
        String professionalSummary,
        List<GeneratedCvSkill> skills,
        List<GeneratedCvExperience> experiences,
        List<String> languages
) {

    public GeneratedCv {
        if (headline == null || headline.isBlank()) {
            throw new IllegalArgumentException("Generated CV headline must not be blank");
        }
        if (professionalSummary == null || professionalSummary.isBlank()) {
            throw new IllegalArgumentException("Generated CV professional summary must not be blank");
        }
        skills = skills == null ? List.of() : List.copyOf(skills);
        experiences = experiences == null ? List.of() : List.copyOf(experiences);
        languages = languages == null ? List.of() : List.copyOf(languages);
    }
}
